version: "3"
services:
  sql:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
    container_name: sql
