version: "3"
services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:443"
  #     - "44340:80"
  #   container_name: api
  #   depends_on:
  #     - sql
  #   links:
  #     - sql:db

  sql:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
    container_name: sql
